import React from 'react'

export default function index() {
    return (
        <main className="px-4 lg:px-36 py-8 lg:py-20 flex flex-col justify-center bg-gradient-to-br from-gray-600 to-gray-700 text-gray-50">
            <h1 className="text-4xl font-bold uppercase tracking-widest border-b-2 border-gray-400 pb-4 lg:w-1/2 mx-auto text-center">Privacy Policy</h1>

            <div className="text-lg my-4 lg:my-8 lg:w-2/4 mx-auto">
                <p className="text-2xl text-left mb-4">General : </p>
                <p className="mb-4">Please read the following terms and conditions (“Terms of Use”) which govern your use of this Hausdorff-Besicovitch Capital website (the “Site”).  By using the Site, you knowingly and willingly agree to be bound by these Terms of Use, which may be updated from time to time and posted on this Terms of Use page.
                    This Site is intended to provide an overview of Hausdorff-Besicovitch Capital (“HBC”) and is for general information purposes only.  The Site is not intended to provide investing, accounting, tax, legal or any other advice, nor shall any content on this Site be deemed a recommendation that you pursue any investment style or strategy.  If you would like investing, accounting, tax, legal or any other advice, you should consult with your own professional advisors regarding your individual circumstances and needs.
                    Nothing on this Site is intended to constitute an offer to sell or a solicitation of any offer to any securities or other assets, nor should it or any part of it be relied upon in connection with any offer or sale of securities or other assets. Any such offer or solicitation can and will be made only by means of a complete offering memorandum and related subscription materials which contain significant additional information about the terms of an investment, only in jurisdictions in which such an offer would be lawful, and only to individuals who meet the investor sophistication criteria that are determined from time to time by Hausdorff-Besicovitch Capital in its sole and absolute discretion (such documents, the “Offering Documents”). Any decision to invest must be based solely upon the information set forth in the Offering Documents, regardless of any information that may have been otherwise furnished, including this Site.
                    This Site and the information contained herein are provided “as is” and Hausdorff-Besicovitch Capital and its affiliates expressly disclaim all express or implied warranties and representations with respect to the fitness of information contained herein for any particular usage, its merchantability or its application or purpose.
                    Without limiting the foregoing, Hausdorff-Besicovitch Capital does not make any representation or warranty as to the accuracy, adequacy, or completeness of the information and materials contained on this Site or that the Site will operate without interruption or error.  In no event shall Hausdorff-Besicovitch Capital or its affiliates be responsible or liable for the correctness of any such material or damage or lost opportunities resulting from use of this data.</p>

                <p className="mb-4">You acknowledge that by using the Site you may be subject to privacy and security exploitations, including without limitation, the ability of unauthorized persons to intercept or access information transmitted by you through the Site.</p>

                <p className="text-2xl text-left mb-4">Intellectual Property : </p>

                <p className="">Except as otherwise noted, all content and materials on the Site are the property of Hausdorff-Besicovitch Capital and should not be used, modified or reproduced without Hausdorff-Besicovitch Capital’s written consent.  Hausdorff-Besicovitch Capital, and the proprietary logos and marks included on the Site that identify Hausdorff-Besicovitch Capital services and products are registered trademarks in India and other countries and may not be used without the prior written consent of Hausdorff-Besicovitch Capital.
                    Additional Provision for European Users
                    If you are domiciled in or have a registered office in a member state of the European Economic Area (“EEA”) that has implemented the Alternative Investment Fund Managers Directive (Directive 2011/61/EU) in a manner that may impose disclosure, reporting or other obligations on Hausdorff-Besicovitch Capital or its affiliates, you expressly agree and acknowledge that you or any other person or entity you represent initiated the discussion, correspondence or other communications with Hausdorff-Besicovitch Capital or its affiliates or agents, and any information you received regarding any investment funds managed by Hausdorff-Besicovitch Capital was pursuant to your request; and none of Hausdorff-Besicovitch Capital or its affiliates or agents at any time directly or indirectly contacted you with respect to the provision of investment services or investment in any investment fund managed by Hausdorff-Besicovitch Capital or its affiliates prior to such unsolicited initiation of discussions, correspondence or other communications.</p>
            </div>
        </main>
    )
}
